### ISSUE TITLE
Default Location app/Resources/translations

### ISSUE THREAD

**Issue by dahomz** [KilikFr/TranslationBundle#14]
Hi, great bundle! - I found it very useful.

Our translation files were in the app/Resources/translations directory (so none were found)

I just copied them to the Resources/translations/ directory inside our named bundle to find them and all worked as expected.  Maybe worth updating the readme just to mention this.

From the docs:

Translation Resource/File Names and Locations¶

Symfony looks for message files (i.e. translations) in the following default locations:

    the app/Resources/translations directory;
    the app/Resources/<bundle name>/translations directory;
    the Resources/translations/ directory inside of any bundle.

**Comment by mitch10593** [comment]
Hi,
Could you check if the last patch (#13) fixed your problem ?
