### ISSUE TITLE
Newlines in translations not correctly imported

### ISSUE THREAD

**Issue by sandermarechal** [KilikFr/TranslationBundle#3]
When I export a translation like this:
```yaml
key: "foo\n\nbar"
```
and then import it again, it is transformed to this (using single quotes):
```yaml
key: 'foo\n\nbar'
```
The latter means that `\n` is interpreted not as a newline but as a literal slash character followed by the letter `n`.
This makes importing painful because we need to edit the Yaml files after importing to fix it.
Can you fix this?

**Comment by mitch10593** [comment]
fixed by #8
